name: Build Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binaries
        run: |
          make clean
          make build-all

          # Make binaries executable
          chmod +x dist/swa-*

      - name: Delete existing release
        run: |
          gh release delete ${{ github.event.inputs.version }} --yes || true
          git tag -d ${{ github.event.inputs.version }} || true
          git push origin :refs/tags/${{ github.event.inputs.version }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        run: |
          gh release create ${{ github.event.inputs.version }} \
            --title "SWA ${{ github.event.inputs.version }}" \
            --notes "Cross-platform binaries for SWA CLI tool" \
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
