name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build binaries
      run: |
        make clean
        make build-all
        chmod +x bin/awsc-*
    
    - name: Create release
      run: |
        gh release create ${{ steps.version.outputs.VERSION }} \
          --title "AWSC ${{ steps.version.outputs.VERSION }}" \
          --generate-notes \
          bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}